[platformio]
default_envs = mega2560-waveshare          ; or uno-r4-wifi-tfte spi etc.

[env:mega2560-waveshare]
platform   = atmelavr
board      = megaatmega2560
framework  = arduino
lib_deps   =
    ; only list shared deps if any (most are in lib/)
build_flags =
    -D GFX_BACKEND_WAVESHARE_ILI9486
    ; -D GFX_BACKEND_ARDUINO_GFX     ; uncomment ONE only
    ; -D GFX_BACKEND_TFT_eSPI
    ; -D GFX_BACKEND_LVGL
monitor_speed = 115200

[env:unor4wifi-tftespi]
platform   = renesas-ra
board      = uno_r4_wifi
framework  = arduino
build_flags =
    -D GFX_BACKEND_TFT_eSPI
    -D ARDUINO_UNO_R4_WIFI

