[platformio]
default_envs = mega2560-waveshare

[env:mega2560-waveshare]
platform      = atmelavr
board         = megaatmega2560
framework     = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/ImpulseAdventure/Waveshare_ILI9486.git
    moononournation/GFX Library for Arduino
    bodmer/TFT_eSPI
    lvgl/lvgl@^8.3.11                ; older version recommended for AVR/Mega stability

build_flags =
    -D GFX_BACKEND_WAVESHARE_ILI9486   ; ← change only this line to switch backends
    ; -D GFX_BACKEND_ARDUINO_GFX
    ; -D GFX_BACKEND_TFT_eSPI
    ; -D GFX_BACKEND_LVGL
    -I extras
    -D USER_SETUP_LOADED
    -include "User_Setup.h"            ; only active/effective when TFT_eSPI backend selected

[env:unor4wifi-tftespi]
platform      = renesas-ra
board         = uno_r4_wifi
framework     = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/ImpulseAdventure/Waveshare_ILI9486.git
    moononournation/GFX Library for Arduino
    bodmer/TFT_eSPI
    lvgl/lvgl@^8.3.11

build_flags =
    -D GFX_BACKEND_TFT_eSPI
    -D ARDUINO_UNO_R4_WIFI
    -I extras
    -D USER_SETUP_LOADED
    -include "User_Setup.h"
